// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('testProximit', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('testProximit', async function() {
    await driver.get("https://www.proximit.fr/")
    await driver.manage().window().setRect({ width: 1189, height: 696 })
    assert.strictEqual(await driver.findElement(By.css(".home-slider-title")).getText(),"PROXIMIT LABELLISÉE EXPERTCYBER")
  })
})
