// Generated by Selenium IDE
const { Builder, By, Key, until,Select } = require('selenium-webdriver')
const assert = require('assert')
const { expect } = require('chai')
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))
const firefox = require('selenium-webdriver/firefox')

describe('test divers', function() {
  this.timeout(30000)
  let driver
  let vars
  let options = new firefox.Options();

  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()

//    driver = await new Builder().forBrowser('firefox')
//      .setFirefoxOptions(options.addArguments('--headless'))
//      .build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('recherche MUG', async function() {
    await driver.get("http://www.qualifiez.fr/monPrestashop2/prestashop/index.php")
    await driver.manage().window().setRect({ width: 1189, height: 693 })
    await driver.findElement(By.name("s")).click()
    await driver.findElement(By.name("s")).sendKeys("MUG")
    await driver.findElement(By.name("s")).sendKeys(Key.ENTER)
    await driver.wait(until.elementLocated(By.css(".col-lg-5 > p")), 10000)
    assert(await driver.findElement(By.css(".col-lg-5 > p")).getText() == "Il y a 5 produits.")
  })
    it('fenêtre modale + frame +traitement alerte', async function() {
    await driver.get("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert")
    await driver.manage().window().setRect({ width: 1189, height: 693 })
    await driver.findElement(By.id("accept-choices")).click()
    await driver.switchTo().frame("iframeResult")
    await driver.findElement(By.css("body > button")).click()
    let alert=await driver.switchTo().alert()
    const alertText = await alert.getText()
    expect(alertText).to.include('Hello! I am an alert box!')
    await alert.accept()
  })
      it('move to + wait', async function() {
    await driver.get("http://www.qualifiez.fr/monPrestashop2/prestashop/index.php")
    await driver.manage().window().setRect({ width: 1189, height: 693 })    
    let elt = await driver.findElement(By.css("#category-4  > a")).isDisplayed()
    assert.ok(!elt)
    let lien = await driver.findElement(By.css("#category-3 > a"))
    await driver.actions()
      .move({origin :lien })
      .perform()
    await driver.wait(until.elementIsVisible(driver.findElement(By.css("#category-4  > a"))),5000)
    assert.ok( await driver.findElement(By.css("#category-4  > a")).isDisplayed())
//    let elt2 = await driver.findElement(By.css("#category-4  > a")).isDisplayed()
//    assert.ok(elt2)
    
  })
        it('javascript executor', async function() {
    await driver.get("http://www.qualifiez.fr/monPrestashop2/prestashop/index.php")
    await driver.manage().window().setRect({ width: 1189, height: 693 })
    await driver.findElement(By.name("s")).click()
    await driver.executeScript("const input = document.querySelector(`input[name=\"s\"]`);input.value=\"MUG\"")
    await driver.findElement(By.name("s")).sendKeys(Key.ENTER)
    await driver.wait(until.elementLocated(By.css(".col-lg-5 > p")), 10000)
    assert(await driver.findElement(By.css(".col-lg-5 > p")).getText() == "Il y a 5 produits.")
 
  })
  it('should detect if an element is selected', async () => {
    await driver.get("https://www.qualifiez.fr/monPrestashop2/prestashop/index.php?id_product=1&id_product_attribute=1&rewrite=hummingbird-printed-t-shirt&controller=product#/1-taille-s/8-couleur-blanc");
    let element = await driver.findElement(By.xpath('//*[@id="group_1"]/option[1]'));
    let isSelected = await element.isSelected();
    assert.strictEqual(isSelected, true, 'The first option should be selected by default');
    let element2 = await driver.findElement(By.xpath('//*[@id="group_1"]'));
    new Select(element2).selectByVisibleText('L');  
//    await driver.wait(until.elementIsVisible(driver.findElement(By.xpath('//*[@id="group_1"]/option[2]'))),5000)
    await driver.wait(until.elementIsSelected(driver.findElement(By.xpath('//*[@id="group_1"]/option[3]'))),5000)
//      await sleep(5000);    
    element = await driver.findElement(By.xpath('//*[@id="group_1"]/option[3]'));
    assert.strictEqual(await element.isSelected(), true, 'The second option should be selected after selection');
});
  it('should detect if an element is checked', async () => {
    await driver.get("https://www.qualifiez.fr/monPrestashop2/prestashop/index.php?id_product=1&id_product_attribute=1&rewrite=hummingbird-printed-t-shirt&controller=product#/1-taille-s/8-couleur-blanc");
    let element = await driver.findElement(By.xpath('//*[@id="group_2"]/li[1]/label/input'));
    let isChecked = await element.isSelected();
    assert.strictEqual(isChecked, true, 'The first option should be selected by default');
});
});
