// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('testProximit', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test recherche MUG', async function() {
    await driver.get("http://prestashop.qualifiez.fr/")
    await driver.manage().window().setRect({ width: 1189, height: 696 })
    await  driver.manage().setTimeouts( { implicit: 5000 } );
  //  assert.strictEqual(await driver.getTitle(),"monPrestashop")
   await driver.wait(until.titleIs("monPrestashop"),5000);
   let champ_recherche = await driver.findElement(By.name("s"))
   await champ_recherche.sendKeys("MUG")
    await champ_recherche.sendKeys(Key.ENTER)
    await driver.wait(until.elementLocated(By.css(".col-lg-5 > p")), 10000)
   assert.strictEqual( await driver.findElement(By.css(".col-lg-5 > p")).getText(),"Il y a 5 produits."); 
   })
    it('test verif value', async function() {
    await driver.get("http://prestashop.qualifiez.fr/")
    await driver.manage().window().setRect({ width: 1189, height: 696 })
    await  driver.manage().setTimeouts( { implicit: 5000 } );
    assert.strictEqual(await driver.getTitle(),"monPrestashop")
    let champ_recherche = await driver.findElement(By.name("s"))
    await champ_recherche.sendKeys("MUG")
    assert.strictEqual(await champ_recherche.getAttribute("value"),"MUG")
  })
    it('test is displayed', async function() {
    await driver.get("http://prestashop.qualifiez.fr/")
    await driver.manage().window().setRect({ width: 1189, height: 696 })
    await  driver.manage().setTimeouts( { implicit: 5000 } );
    assert.strictEqual(await driver.getTitle(),"monPrestashop")
    let champ_recherche = await driver.findElement(By.name("s"))
    await champ_recherche.sendKeys("MUG")
    assert.strictEqual(await champ_recherche.isDisplayed(),true)
  })
    it('test is checked', async function() {
    await driver.get("http://www.qualifiez.fr/monPrestashop2/prestashop/index.php?id_product=1&id_product_attribute=1&rewrite=hummingbird-printed-t-shirt&controller=product#/1-taille-s/8-couleur-blanc")
    await driver.manage().window().setRect({ width: 1189, height: 696 })
    await  driver.manage().setTimeouts( { implicit: 5000 } );
    let couleur = await driver.findElement(By.css("#group_2 > li:nth-child(1) > label > input"))
    assert.strictEqual(await couleur.isSelected(),true)
    let noir = await driver.findElement(By.css("#group_2 > li:nth-child(2) > label > input"))
    noir.click()
    assert.strictEqual(await noir.isSelected(),true)
  })
})
